# Generated by Django 5.2.12 on 2026-03-21 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_auth", "0003_emailtoken_useremail"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitationcode",
            name="code_type",
            field=models.CharField(
                choices=[("admin", "Admin Generated"), ("fission", "Player Fission")],
                default="admin",
                help_text="Code type: admin or fission",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invitationcode",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Agent who created this fission code",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fission_codes_created",
                to="agent_auth.agent",
            ),
        ),
        migrations.AddField(
            model_name="invitationcode",
            name="generation",
            field=models.IntegerField(
                default=0,
                help_text="Depth in invitation chain: 0=admin, 1+=fission generation",
            ),
        ),
        migrations.AlterField(
            model_name="invitationcode",
            name="code",
            field=models.CharField(
                help_text="Invitation code", max_length=32, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="invitationcode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="Creation time"),
        ),
        migrations.AlterField(
            model_name="invitationcode",
            name="is_used",
            field=models.BooleanField(default=False, help_text="Whether used"),
        ),
        migrations.AlterField(
            model_name="invitationcode",
            name="note",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Note (e.g., batch label)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="invitationcode",
            name="used_at",
            field=models.DateTimeField(blank=True, help_text="Usage time", null=True),
        ),
        migrations.AlterField(
            model_name="invitationcode",
            name="used_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Agent who used this code",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invitation_codes",
                to="agent_auth.agent",
            ),
        ),
        migrations.CreateModel(
            name="FissionCodeVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visited_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="First visit time"
                    ),
                ),
                (
                    "agent",
                    models.OneToOneField(
                        help_text="The visiting Agent",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fission_visit",
                        to="agent_auth.agent",
                    ),
                ),
                (
                    "fission_code",
                    models.ForeignKey(
                        blank=True,
                        help_text="The generated fission code",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visit_records",
                        to="agent_auth.invitationcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fission Code Visit",
                "verbose_name_plural": "Fission Code Visits",
                "db_table": "agent_auth_fission_visits",
            },
        ),
        migrations.CreateModel(
            name="InvitationRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Relationship creation time"
                    ),
                ),
                (
                    "code",
                    models.ForeignKey(
                        blank=True,
                        help_text="The invitation code used",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relationships",
                        to="agent_auth.invitationcode",
                    ),
                ),
                (
                    "invitee",
                    models.ForeignKey(
                        help_text="The invitee",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation_received",
                        to="agent_auth.agent",
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        blank=True,
                        help_text="The inviter (fission code creator)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_sent",
                        to="agent_auth.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitation Relationship",
                "verbose_name_plural": "Invitation Relationships",
                "db_table": "agent_auth_invitation_relationships",
                "unique_together": {("invitee",)},
            },
        ),
    ]
